#!/bin/bash

vpn_name=${1:-non_existed_vpn}

osascript -e "
tell application \"System Events\"
    tell current location of network preferences
        set VPNservice to service \"$vpn_name\"
        set isConnected to connected of current configuration of VPNservice
        if not isConnected then
            connect VPNservice
        end if
    end tell
end tell
"

