#! /usr/bin/env bash

FROM_DIR="$1"
TO_DIR="$2"

INTERVAL=10

all_days() {
  echo `/bin/ls $FROM_DIR | egrep -v '\.errors\.csv' | egrep -o '20(0[0-9]|\d{2})[.\_-]?\d{2}[.\_-]?\d{2}' | sort -u`
}

wait_until_all_existing_files_are_imported() {
  while [ "$(any_files_still_not_imported)" == 'true' ]; do
    sleep $INTERVAL
  done
}

any_files_still_not_imported() {
  local total_data_files_number=$(find $TO_DIR -name "*.csv" | egrep -v '\.errors\.csv' | wc -l)
  local total_imported_files_number=$(find $TO_DIR -name "*.csv" | egrep '\.errors\.csv' | wc -l)

  if [ -z "${total_data_files_number}" ]; then
    echo 'false'
  fi

  if [ "x${total_data_files_number}" != "x${total_imported_files_number}" ]; then
    echo 'true'
  else
    echo 'false'
  fi
}

if_already_imported() {
  local date="$1"

  for imported_day in $(imported_days); do
    if [ "$date" == "$imported_day" ]; then
      echo 'true' && return
    fi
  done

  echo 'false'
}

imported_days() {
  echo `/bin/ls $TO_DIR | egrep '\.errors\.csv' | egrep -o '20(0[0-9]|\d{2})[.\_-]?\d{2}[.\_-]?\d{2}' | sort -u`
}

file_size() {
  local filename=$1
  echo $(du -sh $filename | awk '{print $1}')
}

copy_single_file() {
  local filename="$1"
  local size=$(file_size $file)

  printf '# Copyed %6s %s\n' $size $filename
  cp $filename $TO_DIR
}

copy_files() {
  local files=$(find ${FROM_DIR} -name "*${1}*.csv")

  for file in $files; do
    copy_single_file $file
  done
}

main() {
  for day in $(all_days); do
    wait_until_all_existing_files_are_imported

    [ $(if_already_imported $day) == "true" ] && continue

    echo "####################### `date` #######################"
    copy_files ${day}
  done

  echo
  echo "# √ All files copied."
}

main

